//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThePublicNoteBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ArticleLikes = new HashSet<ArticleLike>();
            this.Articles = new HashSet<Article>();
            this.Pictures = new HashSet<Picture>();
        }

        public int Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Bạn phải nhập vào tên đăng nhập")]
        [RegularExpression(@"^[a-zA-Z0-9]+$", ErrorMessage = "Tên đăng nhập không được chứa ký tự đặc biệt hoặc khoảng trống")]
        [MaxLength(50)]
        [MinLength(4, ErrorMessage = "Tên đăng nhập phải trên 4 ký tự")]
        public string UserName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Bạn phải nhập vào mật khẩu")]
        [RegularExpression(@"^[a-zA-Z0-9]+$", ErrorMessage = "Mật khẩu không được chứa ký tự đặc biệt")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Nhập vào tên của bạn")]
        public string FullName { get; set; }
        [Required(ErrorMessage = "Nhập vào địa chỉ email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required(ErrorMessage = "Nhập vào số điện thoại")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Nhập vào địa chỉ")]
        public string Address { get; set; }
        public string Avatar { get; set; }
        public int LevelId { get; set; }
        public bool Active { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleLike> ArticleLikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual UserLevel UserLevel { get; set; }
    }
}
